package org.opencivicdata.api;

/**
 * All exceptions generated by this OpenStates client
 * will be wrapped in this exception class.
 *
 */
public class OpenCivicDataException extends Exception {
	private static final long serialVersionUID = 1L;
	public MethodMap methodMap;
	public ArgMap argMap;
	public Class<?> responseType;

	public OpenCivicDataException (Exception e, MethodMap methodMap, ArgMap argMap, Class<?> responseType ) {
		super(e);
		this.methodMap = methodMap;
		this.argMap = argMap;
		this.responseType = responseType;
	}
	
	public OpenCivicDataException (String msg, MethodMap methodMap, ArgMap argMap, Class<?> responseType) {
		super(msg);
		this.methodMap = methodMap;
		this.argMap = argMap;
		this.responseType = responseType;
	}
	
	public OpenCivicDataException(String msg, Exception e, MethodMap methodMap, ArgMap argMap, Class<?> responseType ) {
		super(msg, e);
		this.methodMap = methodMap;
		this.argMap = argMap;
		this.responseType = responseType;
	}
}
